# Generated by Django 4.1.7 on 2023-03-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=50)),
                ('authentication', models.CharField(max_length=100)),
                ('encryption', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='BSSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSSID', models.CharField(max_length=20)),
                ('signal', models.IntegerField()),
                ('radio', models.CharField(max_length=50)),
                ('band', models.CharField(max_length=50)),
                ('channel', models.IntegerField()),
                ('SSID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.ssid')),
            ],
        ),
    ]
