# Generated by Django 4.1.7 on 2023-05-20 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('network', models.CharField(max_length=50)),
                ('authentication', models.CharField(max_length=100)),
                ('encryption', models.CharField(max_length=20)),
                ('max_signal', models.IntegerField(null=True)),
                ('is_connected', models.BooleanField(null=True)),
            ],
            options={
                'ordering': ['-is_connected', '-max_signal'],
            },
        ),
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=100)),
                ('data_size', models.IntegerField()),
                ('SSID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.ssid')),
            ],
        ),
        migrations.CreateModel(
            name='BSSID',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BSSID', models.CharField(max_length=20)),
                ('signal', models.IntegerField()),
                ('radio', models.CharField(max_length=50)),
                ('band', models.CharField(max_length=50)),
                ('channel', models.IntegerField()),
                ('SSID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mapp.ssid')),
            ],
        ),
    ]
