# Generated by Django 4.1.7 on 2023-05-20 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='devices',
            options={'ordering': ['-data_size']},
        ),
        migrations.AddField(
            model_name='devices',
            name='percent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
