# Generated by Django 4.1.7 on 2023-03-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0002_alter_bssid_signal'),
    ]

    operations = [
        migrations.AddField(
            model_name='ssid',
            name='max_signal',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bssid',
            name='signal',
            field=models.IntegerField(),
        ),
    ]
