# Generated by Django 4.1.7 on 2023-03-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0003_ssid_max_signal_alter_bssid_signal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssid',
            options={'ordering': ['max_signal']},
        ),
    ]
