# Generated by Django 4.1.7 on 2023-03-05 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapp', '0004_alter_ssid_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ssid',
            options={'ordering': ['-max_signal']},
        ),
    ]
